-- ==========================================
-- 001. EXTENSIONS & ENUMS
-- ==========================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "vector"; -- pgvector

-- Enums
CREATE TYPE business_role AS ENUM ('OWNER', 'ADMIN', 'MEMBER', 'EDITOR', 'FINANCE_MANAGER', 'PROCUREMENT', 'SALES', 'HR');
CREATE TYPE opportunity_type AS ENUM ('CUSTOMER', 'SUPPLIER', 'DISTRIBUTOR', 'DEALER', 'INVESTOR', 'PARTNER', 'EMPLOYEE', 'FUNDING', 'SERVICE', 'PROCUREMENT', 'OTHER');
CREATE TYPE match_status AS ENUM ('RECOMMENDED', 'VIEWED', 'INTERESTED', 'CONTACTED', 'CONVERSATION', 'CONNECTED', 'SUCCESS', 'DISMISSED', 'BLOCKED', 'EXPIRED');
CREATE TYPE post_type AS ENUM ('GENERAL', 'PRODUCT', 'REQUIREMENT', 'FUNDING', 'HIRING', 'PARTNERSHIP', 'ACHIEVEMENT', 'ANNOUNCEMENT', 'FACTORY_REEL');
CREATE TYPE application_status AS ENUM ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'DISBURSED');
CREATE TYPE document_status AS ENUM ('PENDING_OCR', 'OCR_COMPLETED', 'VERIFIED', 'REJECTED');
